### ISSUE TITLE
Getting payment status as INCOMPLETE in onPaymentSuccessful()

### ISSUE THREAD

**Issue by moorthysubu** [mposSVK/acceptSDK-Android#12]
Hey,

When try to make a transaction its getting completed successfully and its triggers `onPaymentSuccessful()` method with payment object. but when I try to get the status of the transactions from the payment object its always gives the response as the
"status":"INCOMPLETE",. but when i access the same transactions from the payment history it has a status as "APPROVED". can you tell me when this status will change incomplete to complete or approved?

accept sdk version : 1.5.7
android-extension-spire:1.5.5

Thanks

**Comment by WirecardMobileServices** [comment]
Look on this like on safety feature. 
"status":"INCOMPLETE"  means that transaction is successful, just it went something wrong during confirmation sending from app to back end. Mostly it is like network issue during confirmation. 
You have to just display message about "check in payment history" ..because app was not able to receive response from confirmation request, but data from confirmation can be delivered successfully.

If its "APPROVED" everything ok.
It can go to "REVERSED" ...if data from confirmation request from app side is not delivered to back end side in certain time . << here is this safety feature.

In Case of "REVERSED" state customer should pay again. 
!!! Its mobile point of sale, this can happen. !!!
