### ISSUE TITLE
App does not show the correct amount to the user when price has fractions

### ISSUE THREAD

**Issue by mpost** [mposSVK/acceptSDK-Android#5]
Buying an item for `1.01` shows `1.00` to the user although the correct amount is processed internally. Bug can be found here: https://github.com/mposSVK/acceptSDK-Android/blob/master/demo/demo/sample/src/main/java/de/wirecard/accept/sample/AbstractPaymentFlowActivity.java#L179

**Comment by WirecardMobileServices** [comment]
Yes, wrong preparing mock data in demo app.
pls use: 
new Bigdecimal("1.01")...for add amount of item, and 
AcceptSDK.getPaymentTotalAmount().scaleByPowerOfTen(amountCurrency.getDefaultFractionDigits())
for preparing amount units

Demo App is using amount "10.0" ;)
thx. Good point

Will be fixed in new version soon.
