### ISSUE TITLE
Thyron implementation can be stuck on signature confirmation dialog

### ISSUE THREAD

**Issue by mpost** [mposSVK/acceptSDK-Android#6]
The Thyron connector does not show buttons when confirming a signature. If the merchant rejects the signature on the scanner device the confirmation dialog can not be closed anymore leaving the app stuck on the dialog.

https://github.com/mposSVK/acceptSDK-Android/blob/master/demo/demo/sample/src/flavor_thyron/java/de/wirecard/accept/sample/PaymentFlowActivity.java#L15

https://github.com/mposSVK/acceptSDK-Android/blob/master/demo/demo/sample/src/main/java/de/wirecard/accept/sample/PaymentFlowDialogs.java#L84

**Comment by WirecardMobileServices** [comment]
Good job mpost. This is demo app, its like example of implementation...not real production app.(Still you have no chance to get stack because to continue or cancel you need press some action buttons on terminal(hardware)... it mean that you are confirming or decline signature on terminal... like remote control of app ;) )
thx.

**Comment by mpost** [comment]
Agreed but the cancel button on the device does not continue the app.
